name: Metrics
on:
  schedule: [{cron: "0 0 * * 0"}]
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, metadata
          config_timezone: Europe/Lisbon
          # Suggested plugins
          plugin_languages_indepth: yes
          plugin_languages_details: lines, percentage
          plugin_languages_limit: 8
          plugin_languages_analysis_timeout: 15
          plugin_languages: yes
          plugin_languages_categories: 8
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          template: classic
          config_twemoji: yes
