name: Metrics
on:
  schedule: [{cron: "0 0 * * 0"}]
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, metadata
          config_timezone: Europe/Lisbon
          # Plugins
          plugin_languages: yes
          plugin_languages_details: percentage

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          template: classic
          config_twemoji: yes
        env:
            COMMIT_MESSAGE: 'docs: update metrics file {{ github.run_id }}'
